exclude:
  - README.markdown
  - LICENSE
  - Makefile
  - main.js
  - node_modules
  - package.json
  - deploy.sh
  - src
  - assets/mission-control.js.map
  - webpack.config.js
  - assets/style.css.map
